// ==============================================================================
// DOCTOR-LABS SUPERFILTER BUILD SCRIPT
// ==============================================================================
// Version: 2026.03.23
// Compliance: ALN-NanoNet HyperSafe Construct | EU AI Act | Neurorights Framework
// Purpose: Generate compile-time version information and build metadata
// ==============================================================================

//! Build script for doctor_labs_superfilter crate.
//!
//! This script generates compile-time constants for:
//! - Crate version and build information
//! - Git commit hash and branch information
//! - Build timestamp and environment details
//! - Compliance framework markers
//! - Feature flag status
//!
//! Generated code is output to OUT_DIR/build_info.rs and included in lib.rs.

#![deny(clippy::all)]
#![warn(missing_docs)]

use std::env;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::path::Path;
use std::process::Command;
use std::time::{SystemTime, UNIX_EPOCH};

// ==============================================================================
// MAIN BUILD FUNCTION
// ==============================================================================

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=.git/HEAD");

    // Create output directory
    let out_dir = env::var("OUT_DIR")?;
    let dest_path = Path::new(&out_dir).join("build_info.rs");
    let mut file = BufWriter::new(File::create(&dest_path)?);

    println!("cargo:warning=Doctor-Labs SuperFilter Build Script Starting...");

    // Generate all build information
    generate_crate_info(&mut file)?;
    generate_git_info(&mut file)?;
    generate_build_info(&mut file)?;
    generate_compliance_info(&mut file)?;
    generate_feature_info(&mut file)?;
    generate_platform_info(&mut file)?;

    // Flush and sync
    file.flush()?;
    file.sync_all()?;

    println!("cargo:warning=Doctor-Labs SuperFilter Build Script Complete.");
    println!("cargo:warning=Build info written to: {}", dest_path.display());

    Ok(())
}

// ==============================================================================
// CRATE INFORMATION GENERATION
// ==============================================================================

/// Generate crate metadata from Cargo environment variables.
fn generate_crate_info(file: &mut BufWriter<File>) -> std::io::Result<()> {
    writeln!(file, "// =============================================================================")?;
    writeln!(file, "// CRATE INFORMATION (Auto-generated by build.rs)")
?;
    writeln!(file, "// =============================================================================")?;
    writeln!(file)?;

    // Crate name
    let crate_name = env::var("CARGO_PKG_NAME").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Crate name")?;
    writeln!(file, "pub const CRATE_NAME: &str = \"{}\";", crate_name)?;
    writeln!(file)?;

    // Crate version
    let crate_version = env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".to_string());
    writeln!(file, "/// Crate version")?;
    writeln!(file, "pub const CRATE_VERSION: &str = \"{}\";", crate_version)?;
    writeln!(file)?;

    // Crate authors
    let crate_authors = env::var("CARGO_PKG_AUTHORS").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Crate authors")?;
    writeln!(file, "pub const CRATE_AUTHORS: &str = \"{}\";", crate_authors)?;
    writeln!(file)?;

    // Crate description
    let crate_description = env::var("CARGO_PKG_DESCRIPTION").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Crate description")?;
    writeln!(file, "pub const CRATE_DESCRIPTION: &str = \"{}\";", crate_description)?;
    writeln!(file)?;

    // Crate homepage
    let crate_homepage = env::var("CARGO_PKG_HOMEPAGE").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Crate homepage")?;
    writeln!(file, "pub const CRATE_HOMEPAGE: &str = \"{}\";", crate_homepage)?;
    writeln!(file)?;

    // Crate repository
    let crate_repository = env::var("CARGO_PKG_REPOSITORY").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Crate repository")?;
    writeln!(file, "pub const CRATE_REPOSITORY: &str = \"{}\";", crate_repository)?;
    writeln!(file)?;

    // Crate license
    let crate_license = env::var("CARGO_PKG_LICENSE").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Crate license")?;
    writeln!(file, "pub const CRATE_LICENSE: &str = \"{}\";", crate_license)?;
    writeln!(file)?;

    // Rust version
    let rust_version = env::var("CARGO_PKG_RUST_VERSION").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Minimum Rust version")?;
    writeln!(file, "pub const RUST_VERSION: &str = \"{}\";", rust_version)?;
    writeln!(file)?;

    // Edition
    let edition = env::var("CARGO_MANIFEST_DIR")
        .map(|_| "2021".to_string())
        .unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Rust edition")?;
    writeln!(file, "pub const RUST_EDITION: &str = \"{}\";", edition)?;
    writeln!(file)?;

    Ok(())
}

// ==============================================================================
// GIT INFORMATION GENERATION
// ==============================================================================

/// Generate Git repository information.
fn generate_git_info(file: &mut BufWriter<File>) -> std::io::Result<()> {
    writeln!(file, "// =============================================================================")?;
    writeln!(file, "// GIT INFORMATION (Auto-generated by build.rs)")?;
    writeln!(file, "// =============================================================================")?;
    writeln!(file)?;

    // Git commit hash (short)
    let git_hash = get_git_hash_short().unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Git commit hash (short)")?;
    writeln!(file, "pub const GIT_HASH_SHORT: &str = \"{}\";", git_hash)?;
    writeln!(file)?;

    // Git commit hash (full)
    let git_hash_full = get_git_hash_full().unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Git commit hash (full)")?;
    writeln!(file, "pub const GIT_HASH_FULL: &str = \"{}\";", git_hash_full)?;
    writeln!(file)?;

    // Git branch
    let git_branch = get_git_branch().unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Git branch")?;
    writeln!(file, "pub const GIT_BRANCH: &str = \"{}\";", git_branch)?;
    writeln!(file)?;

    // Git dirty status
    let git_dirty = is_git_dirty().unwrap_or(false);
    writeln!(file, "/// Git working tree dirty status")?;
    writeln!(file, "pub const GIT_DIRTY: bool = {};", git_dirty)?;
    writeln!(file)?;

    // Git commit timestamp
    let git_timestamp = get_git_commit_timestamp().unwrap_or_else(|_| "0".to_string());
    writeln!(file, "/// Git commit timestamp (UNIX epoch)")?;
    writeln!(file, "pub const GIT_COMMIT_TIMESTAMP: &str = \"{}\";", git_timestamp)?;
    writeln!(file)?;

    // Git tags
    let git_tags = get_git_tags().unwrap_or_else(|_| "none".to_string());
    writeln!(file, "/// Git tags at commit")?;
    writeln!(file, "pub const GIT_TAGS: &str = \"{}\";", git_tags)?;
    writeln!(file)?;

    Ok(())
}

// ==============================================================================
// BUILD INFORMATION GENERATION
// ==============================================================================

/// Generate build timestamp and environment information.
fn generate_build_info(file: &mut BufWriter<File>) -> std::io::Result<()> {
    writeln!(file, "// =============================================================================")?;
    writeln!(file, "// BUILD INFORMATION (Auto-generated by build.rs)")?;
    writeln!(file, "// =============================================================================")?;
    writeln!(file)?;

    // Build timestamp (UNIX epoch milliseconds)
    let build_timestamp_ms = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_millis();
    writeln!(file, "/// Build timestamp (UNIX epoch milliseconds)")?;
    writeln!(file, "pub const BUILD_TIMESTAMP_MS: u128 = {};", build_timestamp_ms)?;
    writeln!(file)?;

    // Build timestamp (ISO 8601)
    let build_timestamp_iso = chrono::Utc::now().format("%Y-%m-%dT%H:%M:%SZ").to_string();
    writeln!(file, "/// Build timestamp (ISO 8601)")?;
    writeln!(file, "pub const BUILD_TIMESTAMP_ISO: &str = \"{}\";", build_timestamp_iso)?;
    writeln!(file)?;

    // Build profile (debug/release)
    let profile = env::var("PROFILE").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Build profile")?;
    writeln!(file, "pub const BUILD_PROFILE: &str = \"{}\";", profile)?;
    writeln!(file)?;

    // Optimization level
    let opt_level = env::var("OPT_LEVEL").unwrap_or_else(|_| "0".to_string());
    writeln!(file, "/// Optimization level")?;
    writeln!(file, "pub const BUILD_OPT_LEVEL: &str = \"{}\";", opt_level)?;
    writeln!(file)?;

    // Debug assertions
    let debug_assertions = env::var("DEBUG").unwrap_or_else(|_| "true".to_string()) == "true";
    writeln!(file, "/// Debug assertions enabled")?;
    writeln!(file, "pub const BUILD_DEBUG_ASSERTIONS: bool = {};", debug_assertions)?;
    writeln!(file)?;

    // Target triple
    let target = env::var("TARGET").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Build target triple")?;
    writeln!(file, "pub const BUILD_TARGET: &str = \"{}\";", target)?;
    writeln!(file)?;

    // Host triple
    let host = env::var("HOST").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Build host triple")?;
    writeln!(file, "pub const BUILD_HOST: &str = \"{}\";", host)?;
    writeln!(file)?;

    // Number of CPUs
    let num_cpus = num_cpus::get();
    writeln!(file, "/// Number of CPUs used for build")?;
    writeln!(file, "pub const BUILD_NUM_CPUS: usize = {};", num_cpus)?;
    writeln!(file)?;

    Ok(())
}

// ==============================================================================
// COMPLIANCE INFORMATION GENERATION
// ==============================================================================

/// Generate compliance framework markers.
fn generate_compliance_info(file: &mut BufWriter<File>) -> std::io::Result<()> {
    writeln!(file, "// =============================================================================")?;
    writeln!(file, "// COMPLIANCE INFORMATION (Auto-generated by build.rs)")?;
    writeln!(file, "// =============================================================================")?;
    writeln!(file)?;

    // ALN-NanoNet HyperSafe Construct compliance
    writeln!(file, "/// ALN-NanoNet HyperSafe Construct compliance marker")?;
    writeln!(file, "pub const COMPLIANCE_ALN_HYPER_SAFE: bool = true;")?;
    writeln!(file)?;

    // EU AI Act high-risk classification
    writeln!(file, "/// EU AI Act high-risk system classification")?;
    writeln!(file, "pub const COMPLIANCE_EU_AI_ACT_HIGH_RISK: bool = true;")?;
    writeln!(file)?;

    // Neurorights framework alignment
    writeln!(file, "/// Neurorights framework alignment")?;
    writeln!(file, "pub const COMPLIANCE_NEURORIGHTS_ALIGNED: bool = true;")?;
    writeln!(file)?;

    // GDPR compliance
    writeln!(file, "/// GDPR personal data protection compliance")?;
    writeln!(file, "pub const COMPLIANCE_GDPR: bool = true;")?;
    writeln!(file)?;

    // IEEE ethical standards
    writeln!(file, "/// IEEE P7000 series ethical alignment")?;
    writeln!(file, "pub const COMPLIANCE_IEEE_ETHICAL: bool = true;")?;
    writeln!(file)?;

    // Compliance version
    writeln!(file, "/// Compliance framework version")?;
    writeln!(file, "pub const COMPLIANCE_VERSION: &str = \"2026.03.23\";")?;
    writeln!(file)?;

    // Audit retention period (days)
    writeln!(file, "/// Default audit retention period (days)")?;
    writeln!(file, "pub const COMPLIANCE_AUDIT_RETENTION_DAYS: u32 = 2555;")?;
    writeln!(file)?;

    Ok(())
}

// ==============================================================================
// FEATURE INFORMATION GENERATION
// ==============================================================================

/// Generate feature flag status.
fn generate_feature_info(file: &mut BufWriter<File>) -> std::io::Result<()> {
    writeln!(file, "// =============================================================================")?;
    writeln!(file, "// FEATURE INFORMATION (Auto-generated by build.rs)")?;
    writeln!(file, "// =============================================================================")?;
    writeln!(file)?;

    // Standard library
    writeln!(file, "/// Standard library support enabled")?;
    writeln!(file, "#[cfg(feature = \"std\")]")?;
    writeln!(file, "pub const FEATURE_STD: bool = true;")?;
    writeln!(file, "#[cfg(not(feature = \"std\"))]")?;
    writeln!(file, "pub const FEATURE_STD: bool = false;")?;
    writeln!(file)?;

    // Async runtime
    writeln!(file, "/// Async runtime support enabled")?;
    writeln!(file, "#[cfg(feature = \"async\")]")?;
    writeln!(file, "pub const FEATURE_ASYNC: bool = true;")?;
    writeln!(file, "#[cfg(not(feature = \"async\"))]")?;
    writeln!(file, "pub const FEATURE_ASYNC: bool = false;")?;
    writeln!(file)?;

    // HTTP client
    writeln!(file, "/// HTTP client support enabled")?;
    writeln!(file, "#[cfg(feature = \"http-client\")]")?;
    writeln!(file, "pub const FEATURE_HTTP_CLIENT: bool = true;")?;
    writeln!(file, "#[cfg(not(feature = \"http-client\"))]")?;
    writeln!(file, "pub const FEATURE_HTTP_CLIENT: bool = false;")?;
    writeln!(file)?;

    // Configuration files
    writeln!(file, "/// Configuration file support enabled")?;
    writeln!(file, "#[cfg(feature = \"config-files\")]")?;
    writeln!(file, "pub const FEATURE_CONFIG_FILES: bool = true;")?;
    writeln!(file, "#[cfg(not(feature = \"config-files\"))]")?;
    writeln!(file, "pub const FEATURE_CONFIG_FILES: bool = false;")?;
    writeln!(file)?;

    // Metrics
    writeln!(file, "/// Metrics and monitoring enabled")?;
    writeln!(file, "#[cfg(feature = \"metrics\")]")?;
    writeln!(file, "pub const FEATURE_METRICS: bool = true;")?;
    writeln!(file, "#[cfg(not(feature = \"metrics\"))]")?;
    writeln!(file, "pub const FEATURE_METRICS: bool = false;")?;
    writeln!(file)?;

    // Production hardening
    writeln!(file, "/// Production hardening enabled")?;
    writeln!(file, "#[cfg(feature = \"production\")]")?;
    writeln!(file, "pub const FEATURE_PRODUCTION: bool = true;")?;
    writeln!(file, "#[cfg(not(feature = \"production\"))]")?;
    writeln!(file, "pub const FEATURE_PRODUCTION: bool = false;")?;
    writeln!(file)?;

    Ok(())
}

// ==============================================================================
// PLATFORM INFORMATION GENERATION
// ==============================================================================

/// Generate platform-specific information.
fn generate_platform_info(file: &mut BufWriter<File>) -> std::io::Result<()> {
    writeln!(file, "// =============================================================================")?;
    writeln!(file, "// PLATFORM INFORMATION (Auto-generated by build.rs)")?;
    writeln!(file, "// =============================================================================")?;
    writeln!(file)?;

    // Operating system
    let os = env::var("CARGO_CFG_TARGET_OS").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Target operating system")?;
    writeln!(file, "pub const PLATFORM_OS: &str = \"{}\";", os)?;
    writeln!(file)?;

    // Architecture
    let arch = env::var("CARGO_CFG_TARGET_ARCH").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Target architecture")?;
    writeln!(file, "pub const PLATFORM_ARCH: &str = \"{}\";", arch)?;
    writeln!(file)?;

    // Environment
    let env = env::var("CARGO_CFG_TARGET_ENV").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Target environment")?;
    writeln!(file, "pub const PLATFORM_ENV: &str = \"{}\";", env)?;
    writeln!(file)?;

    // Vendor
    let vendor = env::var("CARGO_CFG_TARGET_VENDOR").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Target vendor")?;
    writeln!(file, "pub const PLATFORM_VENDOR: &str = \"{}\";", vendor)?;
    writeln!(file)?;

    // Pointer width
    let pointer_width = env::var("CARGO_CFG_TARGET_POINTER_WIDTH").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Target pointer width (bits)")?;
    writeln!(file, "pub const PLATFORM_POINTER_WIDTH: &str = \"{}\";", pointer_width)?;
    writeln!(file)?;

    // Endianness
    let endianness = env::var("CARGO_CFG_TARGET_ENDIAN").unwrap_or_else(|_| "unknown".to_string());
    writeln!(file, "/// Target endianness")?;
    writeln!(file, "pub const PLATFORM_ENDIAN: &str = \"{}\";", endianness)?;
    writeln!(file)?;

    Ok(())
}

// ==============================================================================
// GIT HELPER FUNCTIONS
// ==============================================================================

/// Get short Git commit hash.
fn get_git_hash_short() -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .output()?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        Err("Failed to get git hash".into())
    }
}

/// Get full Git commit hash.
fn get_git_hash_full() -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        Err("Failed to get git hash full".into())
    }
}

/// Get Git branch name.
fn get_git_branch() -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("git")
        .args(["rev-parse", "--abbrev-ref", "HEAD"])
        .output()?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        Err("Failed to get git branch".into())
    }
}

/// Check if Git working tree is dirty.
fn is_git_dirty() -> Result<bool, Box<dyn std::error::Error>> {
    let output = Command::new("git")
        .args(["status", "--porcelain"])
        .output()?;

    if output.status.success() {
        Ok(!String::from_utf8_lossy(&output.stdout).trim().is_empty())
    } else {
        Ok(false)
    }
}

/// Get Git commit timestamp.
fn get_git_commit_timestamp() -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("git")
        .args(["log", "-1", "--format=%ct"])
        .output()?;

    if output.status.success() {
        Ok(String::from_utf8_lossy(&output.stdout).trim().to_string())
    } else {
        Err("Failed to get git timestamp".into())
    }
}

/// Get Git tags at current commit.
fn get_git_tags() -> Result<String, Box<dyn std::error::Error>> {
    let output = Command::new("git")
        .args(["tag", "--points-at", "HEAD"])
        .output()?;

    if output.status.success() {
        let tags = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if tags.is_empty() {
            Ok("none".to_string())
        } else {
            Ok(tags.replace('\n', ", "))
        }
    } else {
        Ok("none".to_string())
    }
}

// ==============================================================================
// ADDITIONAL BUILD DEPENDENCIES
// ==============================================================================

// Note: These dependencies must be added to [build-dependencies] in Cargo.toml:
// - chrono = "0.4"
// - num_cpus = "1.16"

// ==============================================================================
// END OF BUILD SCRIPT
// ==============================================================================
